export default {
  // 购物车
  CART_AMOUNT_INCREMENT: 'CART_AMOUNT_INCREMENT',
  CART_AMOUNT_DECREMENT: 'CART_AMOUNT_DECREMENT',

  // blog的加载 穿插axios
  START_FETCH_BLOG_LIST: 'START_FETCH_BLOG_LIST',
  FETCH_BLOG_LIST_SUCCESS: 'FETCH_BLOG_LIST_SUCCESS',
  FETCH_BLOG_LIST_FAILED: 'FETCH_BLOG_LIST_FAILED'
}